---
title: "Pct_positivity_sims"
output: html_document
---
```{r, cache=TRUE, message=FALSE, warning=FALSE, echo=FALSE}
setwd("~/Dropbox/COVID-BaltimoreCity/output_20200413")

require(socialmixr)
require(xlsx)
require(magrittr)
require(stringr)
require(reshape2)
require(dplyr)
require(ggplot2) 
require(tidyr)
require(xtable)
require(cowplot)
require(stringr)
require(RcppRoll)
require(extraDistr)
##load data
complete_scenarioA <- read.csv("scenarioA_moderate.csv")
complete_scenarioB <- read.csv("scenarioB_mod_degrading.csv")
complete_scenarioC <- read.csv("scenarioC_mod_degrading_scl.csv")
complete_scenarioD <- read.csv("scenarioD_total_reopen.csv")

n_sims<- 1000
n_days<- 300


#first extract at each timepoint all incident infected people, we have asymptomatic totals and symptomatic totals and total 


get_complete_incid<- function(complete_scenario,n_days,n_sims){
  summed_cat<- matrix(NA,nrow=n_sims*n_days,ncol=3) 
  
  summed_cat[,1]<- apply(complete_scenario[,74:87],1,sum)
  summed_cat[,2]<- apply(complete_scenario[,88:101],1,sum)
  summed_cat[,3]<- apply(complete_scenario[,74:101],1,sum)
  
  summed_cat<- as.data.frame(summed_cat)
  colnames(summed_cat)<- c("Incid_Asymp","Incid_Symp","Incid_Total")
  
  complete_incid<- summed_cat%>%
    mutate(Days= rep(1:n_days,times=n_sims))%>%
    mutate(Sim_Index= rep(1:n_sims,each=n_days))
    
return(complete_incid)
} 

complete_incidentA<- get_complete_incid(complete_scenarioA,n_days,n_sims)

complete_incidentB<- get_complete_incid(complete_scenarioB,n_days,n_sims)

complete_incidentC<- get_complete_incid(complete_scenarioC,n_days,n_sims)

complete_incidentD<- get_complete_incid(complete_scenarioD,n_days,n_sims)


```

```{r, cache=TRUE, message=FALSE, warning=FALSE, echo=FALSE}

#start with just testing symptomatics

#suppose each of the symptomatics start showing symptoms at day 5 (can be adjusted to be random)


#we would test when they developed symptoms, and assume that the test takes 3 days to come back. The denominator would be tests that have "come back" i.e. you wouldn't count a test in the denominator on the day it was conducted but rather on the day we got a result for it. 

#want to know how many tests are being run on symptomatic positives each day, build in a sens of 0.99- 0.95% to count the positive tests, then count person-days where people are infectious and not tested (we don't know about them).

#suppose we manage to test 90% of symptomatic people



get_symptomatic_tests<- function(complete_incident, n_days, n_sims, sens, prop_tested){
  
  untested_person_time<- matrix(NA, nrow=(n_days*n_sims),ncol=1)
    
    for(i in 1:n_sims){
      untested_person_time[which(complete_incident$Sim_Index==i),1]<- 
    roll_sum(complete_incident$Incid_Symp[which(complete_incident$Sim_Index==i)],8,fill=NA)
    }
  untested_person_time<- as.data.frame(untested_person_time)
  colnames(untested_person_time)<- c('Untested_person_time')
  
  
  
  symptomatic_tests<- complete_incident%>%
    mutate(Symp_Day=Days+5)%>%
    mutate(Test_return_Day=Symp_Day+3)%>%
    mutate(Num_tests=prop_tested*Incid_Symp)%>%
    mutate(Num_pos_tests=sens*Num_tests)%>%
    mutate(Num_false_neg_test= Num_tests-Num_pos_tests)%>%
    mutate(False_neg_person_time= roll_sum(Num_false_neg_test,10,fill=NA))%>%
    mutate(symp_untested_person_time=roll_sum(Incid_Symp-Num_tests,10,fill=NA))
    
  symptomatic_testing<- left_join(complete_incident,symptomatic_tests,by=c("Days"="Test_return_Day","Sim_Index"="Sim_Index"))
  
  untested_person_time<- untested_person_time%>%
    mutate(Days=rep(1:n_days,times=n_sims))%>%
  mutate(Sim_Index=rep(1:n_sims,each=n_days))%>%
    mutate(missing_person_time=Untested_person_time+symptomatic_testing$symp_untested_person_time)
  
  symptomatic_testing<- symptomatic_testing%>%
  mutate_all(~replace(., is.na(.), 0))
  
    untested_person_time<- untested_person_time%>%
    mutate_all(~replace(., is.na(.), 0))
return(list(symptomatic_testing,untested_person_time))
}

symptomatic_testsA<- get_symptomatic_tests(complete_incidentA,n_days,n_sims,0.95,0.7)

symptomatic_testsB<- get_symptomatic_tests(complete_incidentB,n_days,n_sims,0.95,0.7)


symptomatic_testsA_60<- get_symptomatic_tests(complete_incidentA,n_days,n_sims,0.95,0.6)

symptomatic_testsB_60<- get_symptomatic_tests(complete_incidentB,n_days,n_sims,0.95,0.6)


symptomatic_testsC<- get_symptomatic_tests(complete_incidentC,n_days,n_sims,0.95,0.7)

symptomatic_testsD<- get_symptomatic_tests(complete_incidentD,n_days,n_sims,0.95,0.7)


#############################
#now we need to simulate testing people who might have symptoms of COVID but its something else and not covid

vector_num_tests<- rep(c(rep(10,10),rep(20,10),rep(40,20),rep(80,20),rep(120,20),
                     rep(240,20),rep(480,20),rep(960,20),rep(1920,20),rep(3840,20),
                     rep(7680,20),rep(11500,100)),times=n_sims)
get_false_positives<- function(complete_incident, sypmtomatic_tests,num_tests,n_days,n_sims,specificity){
  
  false_positives<- matrix(NA,nrow=n_sims*n_days, ncol=2)
  
 false_positives[,1]<- num_tests- sypmtomatic_tests$Num_tests
  false_positives[,2]<- (1-specificity)*false_positives[,1]
  
  false_positives<-as.data.frame(false_positives)
  
  colnames(false_positives)<- c("Tests_done","Num_false_positive")
  
  return(false_positives)
  
}

false_positivesA<-get_false_positives(complete_incidentA,symptomatic_testsA[[1]],vector_num_tests,n_days,n_sims,0.98)

false_positivesB<-get_false_positives(complete_incidentB,symptomatic_testsB[[1]],vector_num_tests,n_days,n_sims,0.98)

false_positivesA_60<-get_false_positives(complete_incidentA,symptomatic_testsA_60[[1]],vector_num_tests,n_days,n_sims,0.98)

false_positivesB_60<-get_false_positives(complete_incidentB,symptomatic_testsB_60[[1]],vector_num_tests,n_days,n_sims,0.98)


false_positivesC<-get_false_positives(complete_incidentC,symptomatic_testsC[[1]],vector_num_tests,n_days,n_sims,0.98)

false_positivesD<-get_false_positives(complete_incidentD,symptomatic_testsD[[1]],vector_num_tests,n_days,n_sims,0.98)
#################################

#calculate positive rate: 

get_pos_rate<- function(complete_incident,symptomatic_tests,false_positives,num_tests,n_days,n_sims){
  pos_rate<- matrix(NA,nrow=n_sims*n_days,ncol=1)
  
  pos_rate[,1]<- (symptomatic_tests$Num_pos_tests+false_positives$Num_false_positive)/num_tests
  
  pos_rate<-as.data.frame(pos_rate)
  
  colnames(pos_rate)<- c("Test_Positive_rate")
  
  pos_rate<- pos_rate%>%
    mutate(Date=rep(1:n_days,times=n_sims))%>%
    mutate(Sim_Index=rep(1:n_sims,each=n_days))
  
  return(pos_rate)
}

pos_rateA<- get_pos_rate(complete_incidentA,symptomatic_testsA[[1]],false_positivesA,vector_num_tests,n_days,n_sims)

pos_rateB<- get_pos_rate(complete_incidentB,symptomatic_testsB[[1]],false_positivesB,vector_num_tests,n_days,n_sims)

pos_rateA_60<- get_pos_rate(complete_incidentA,symptomatic_testsA_60[[1]],false_positivesA_60,vector_num_tests,n_days,n_sims)

pos_rateB_60<- get_pos_rate(complete_incidentB,symptomatic_testsB_60[[1]],false_positivesB_60,vector_num_tests,n_days,n_sims)

pos_rateC<- get_pos_rate(complete_incidentC,symptomatic_testsC[[1]],false_positivesC,vector_num_tests,n_days,n_sims)

pos_rateD<- get_pos_rate(complete_incidentD,symptomatic_testsD[[1]],false_positivesD,vector_num_tests,n_days,n_sims)
################################

#how many person hours of infectiousness are we missing?

total_missing_person_timeA<-matrix(NA,nrow=n_sims*n_days,ncol=1)

for(i in 1:n_sims){
total_missing_person_timeA[which(complete_incidentA$Sim_Index==i),1]<- cumsum(symptomatic_testsA[[2]]$missing_person_time[which(complete_incidentC$Sim_Index==i)])
}

total_missing_person_timeA<- as.data.frame(total_missing_person_timeA)

colnames(total_missing_person_timeA)<- c("Missing_Person_Time")

total_missing_person_timeA<- total_missing_person_timeA%>%
  mutate(Day=rep(1:n_days,times=n_sims))%>%
  mutate(Sim_Index=rep(1:n_sims,each=n_days))


total_missing_person_timeA_60<-matrix(NA,nrow=n_sims*n_days,ncol=1)

for(i in 1:n_sims){
total_missing_person_timeA_60[which(complete_incidentA$Sim_Index==i),1]<- cumsum(symptomatic_testsA_60[[2]]$missing_person_time[which(complete_incidentC$Sim_Index==i)])
}

total_missing_person_timeA_60<- as.data.frame(total_missing_person_timeA_60)

colnames(total_missing_person_timeA_60)<- c("Missing_Person_Time")

total_missing_person_timeA_60<- total_missing_person_timeA_60%>%
  mutate(Day=rep(1:n_days,times=n_sims))%>%
  mutate(Sim_Index=rep(1:n_sims,each=n_days))


total_missing_person_timeB<-matrix(NA,nrow=n_sims*n_days,ncol=1)

for(i in 1:n_sims){
total_missing_person_timeB[which(complete_incidentB$Sim_Index==i),1]<- cumsum(symptomatic_testsB[[2]]$missing_person_time[which(complete_incidentB$Sim_Index==i)])
}

total_missing_person_timeB<- as.data.frame(total_missing_person_timeB)

colnames(total_missing_person_timeB)<- c("Missing_Person_Time")

total_missing_person_timeB<- total_missing_person_timeB%>%
  mutate(Day=rep(1:n_days,times=n_sims))%>%
  mutate(Sim_Index=rep(1:n_sims,each=n_days))

total_missing_person_timeB_60<-matrix(NA,nrow=n_sims*n_days,ncol=1)

for(i in 1:n_sims){
total_missing_person_timeB_60[which(complete_incidentB$Sim_Index==i),1]<- cumsum(symptomatic_testsB_60[[2]]$missing_person_time[which(complete_incidentB$Sim_Index==i)])
}

total_missing_person_timeB_60<- as.data.frame(total_missing_person_timeB_60)

colnames(total_missing_person_timeB_60)<- c("Missing_Person_Time")

total_missing_person_timeB_60<- total_missing_person_timeB_60%>%
  mutate(Day=rep(1:n_days,times=n_sims))%>%
  mutate(Sim_Index=rep(1:n_sims,each=n_days))


total_missing_person_timeC<-matrix(NA,nrow=n_sims*n_days,ncol=1)

for(i in 1:n_sims){
total_missing_person_timeC[which(complete_incidentC$Sim_Index==i),1]<- cumsum(symptomatic_testsC[[2]]$missing_person_time[which(complete_incidentC$Sim_Index==i)])
}

total_missing_person_timeC<- as.data.frame(total_missing_person_timeC)

colnames(total_missing_person_timeC)<- c("Missing_Person_Time")

total_missing_person_timeC<- total_missing_person_timeC%>%
  mutate(Day=rep(1:n_days,times=n_sims))%>%
  mutate(Sim_Index=rep(1:n_sims,each=n_days))




total_missing_person_timeD<-matrix(NA,nrow=n_sims*n_days,ncol=1)

for(i in 1:n_sims){
total_missing_person_timeD[which(complete_incidentD$Sim_Index==i),1]<- cumsum(symptomatic_testsD[[2]]$missing_person_time[which(complete_incidentD$Sim_Index==i)])
}

total_missing_person_timeD<- as.data.frame(total_missing_person_timeD)

colnames(total_missing_person_timeD)<- c("Missing_Person_Time")

total_missing_person_timeD<- total_missing_person_timeD%>%
  mutate(Day=rep(1:n_days,times=n_sims))%>%
  mutate(Sim_Index=rep(1:n_sims,each=n_days))


###################################

#get median pos rate and get median number of person days missing (take day-by-day median)

get_median_pos_rate<- function(pos_rate,n_days,n_sims){
  
  median_pos_rate<-matrix(NA,nrow=n_days,ncol=1)
  
  for(i in 1:n_days){
    median_pos_rate[i,1]<-median(pos_rate$Test_Positive_rate[which(pos_rate$Date==i)])
  }
  median_pos_rate<- as.data.frame(median_pos_rate)
  colnames(median_pos_rate)<- c("Median_Test_Pos_Rate")
  median_pos_rate<- median_pos_rate%>%
    mutate(Day=rep(1:n_days))
  
  return(median_pos_rate)
}

median_pos_rateA<- get_median_pos_rate(pos_rateA,n_days,n_sims)

median_pos_rateB<- get_median_pos_rate(pos_rateB,n_days,n_sims)

median_pos_rateA_60<- get_median_pos_rate(pos_rateA_60,n_days,n_sims)

median_pos_rateB_60<- get_median_pos_rate(pos_rateB_60,n_days,n_sims)


median_pos_rateC<- get_median_pos_rate(pos_rateC,n_days,n_sims)

median_pos_rateD<- get_median_pos_rate(pos_rateD,n_days,n_sims)


median_df<- as.data.frame(rbind(median_pos_rateA,median_pos_rateB))

median_df<- median_df%>%
  mutate(Scenario=c(rep("A",times=n_days),rep("B",times=n_days)))

plot_pos_rate<- ggplot()+
  geom_line(data=median_df,aes(x=Day,y=Median_Test_Pos_Rate,color=Scenario))+
  labs(y="Median Test Positivity Rate")+
  geom_hline(yintercept=0.2,col="red")+
  geom_hline(yintercept=0.1,col="purple")+
  geom_hline(yintercept=0.03,col="blue")

plot_pos_rate


median_df_60<- as.data.frame(rbind(median_pos_rateA_60,median_pos_rateB_60))

median_df_60<- median_df_60%>%
  mutate(Scenario=c(rep("A",times=n_days),rep("B",times=n_days)))

plot_pos_rate_60<- ggplot()+
  geom_line(data=median_df_60,aes(x=Day,y=Median_Test_Pos_Rate,color=Scenario))+
  labs(y="Median Test Positivity Rate")+
  geom_hline(yintercept=0.2,col="red")+
  geom_hline(yintercept=0.1,col="purple")+
  geom_hline(yintercept=0.03,col="blue")

plot_pos_rate_60


############################################################

get_median_missing_person_hours<- function(missing_person_time,n_days,n_sims){
  median_missing_person_time<- matrix(NA,nrow=n_days,ncol=1)
  for(i in 1:n_days){
    median_missing_person_time[i,1]<- median(missing_person_time$Missing_Person_Time[which(missing_person_time$Day==i)])
  }
  
  median_missing_person_time<- as.data.frame(median_missing_person_time)
  colnames(median_missing_person_time)<-c("Missing_Person_Time")
  median_missing_person_time<- median_missing_person_time%>%
    mutate(Day=rep(1:n_days))
  
  return(median_missing_person_time)
}

median_missing_person_hoursA<- get_median_missing_person_hours(total_missing_person_timeA,n_days,n_sims)


median_missing_person_hoursB<- get_median_missing_person_hours(total_missing_person_timeB,n_days,n_sims)


median_missing_person_hoursA_60<- get_median_missing_person_hours(total_missing_person_timeA_60,n_days,n_sims)


median_missing_person_hoursB_60<- get_median_missing_person_hours(total_missing_person_timeB_60,n_days,n_sims)


median_df<- as.data.frame(rbind(median_missing_person_hoursA,median_missing_person_hoursB))

median_df<- median_df%>%
  mutate(Scenario=c(rep("A",times=n_days),rep("B",times=n_days)))

plot_missing_person<- ggplot()+
  geom_line(data=median_df,aes(x=Day,y=Missing_Person_Time,color=Scenario))+
  labs(y="Median Person Time of Missed Infectious Days")

plot_missing_person


median_df_60<- as.data.frame(rbind(median_missing_person_hoursA_60,median_missing_person_hoursB_60))

median_df_60<- median_df_60%>%
  mutate(Scenario=c(rep("A",times=n_days),rep("B",times=n_days)))

plot_missing_person_60<- ggplot()+
  geom_line(data=median_df_60,aes(x=Day,y=Missing_Person_Time,color=Scenario))+
  labs(y="Median Person Time of Missed Infectious Days")

plot_missing_person_60
```